---
# tasks file for apache
- name: install Apache
  yum:
    name: httd
    state: latest
  notify: apache_restart

- name: copy apache index file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: copy Apache configuration file
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf

- name: ensure Apache is running
  service:
    name: httpd
    state: started
    enabled: true
